#!/bin/sh

berryc border_width       0
berryc inner_border_width 0
berryc title_height       35
berryc edge_gap           30 30 30 30

berryc inner_focus_color   c9c1bd
berryc inner_unfocus_color e5dcdc

berryc draw_text "false"
berryc smart_place "true"
berryc edge_lock   "true"

pgrep sxhkd || sxhkd -c "$HOME/.config/berry/sxhkdrc" &
